Curator search
BIBSYSDEV/nva-nvi pull request #104
Opened 2023-09-23 09:04 UTC by sondrev

2023-09-25 07:13 UTC, monaullah commented on index-handlers/src/test/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandlerTest.java
>      void shouldReturnDocumentFromIndexContainingSingleHitWhenUsingTerms() throws IOException {
Remove this test?

2023-09-25 10:39 UTC, truhacevkir approved these changes
Ser bra ut

2023-09-25 10:39 UTC, truhacevkir commented on index-handlers/src/main/java/no/sikt/nva/nvi/index/Aggregations.java
> +    }
Can be written using already existent methods:

```
    public static Query contributorQuery(List<String> institutions) {
        return nestedQuery(jsonPathOf(PUBLICATION_DETAILS, CONTRIBUTORS),
                           mustMatch(termsQuery(institutions, jsonPathOf(PUBLICATION_DETAILS, CONTRIBUTORS, AFFILIATIONS))),
                           mustMatch(matchQuery(CREATOR_ROLE, jsonPathOf(PUBLICATION_DETAILS, CONTRIBUTORS, ROLE))));
    }
```

2023-09-25 11:51 UTC, monaullah reviewed
Not sure this will solve the following requirement in the jira-task:
"_...Then the list of candidates should be filtered to candidates with contributors with role creator that are affiliated to the curator's areas of responsibility including sub units_"
Unless frontend sends all sub-units as query params, which is not something we want?

2023-09-26 13:08 UTC, brinxmat requested changes

2023-09-26 13:08 UTC, brinxmat commented on index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/SearchConstants.java
> +                   : mustMatch(appliedQueries);
This is a bit weird, I think the query here is an InstitutionQuery, but the code checks nulls and digs quite deep to do it. I can take a longer look

2023-09-26 13:08 UTC, brinxmat commented on index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/SearchConstants.java
>          return switch (filter) {
This is doing a lot of heavy lifting that is done once per input…see above

2023-09-27 18:50 UTC, brinxmat commented on index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/SearchConstants.java
> +                   : mustMatch(appliedQueries);
Perhaps something like:

```
package no.sikt.nva.nvi.index.aws;

import static java.util.Collections.emptyList;
import static java.util.Objects.isNull;
import static java.util.Objects.nonNull;
import static no.sikt.nva.nvi.index.model.ApprovalStatus.APPROVED;
import static no.sikt.nva.nvi.index.model.ApprovalStatus.PENDING;
import static no.sikt.nva.nvi.index.model.ApprovalStatus.REJECTED;
import static no.sikt.nva.nvi.index.utils.SearchConstants.AFFILIATIONS;
import static no.sikt.nva.nvi.index.utils.SearchConstants.APPROVALS;
import static no.sikt.nva.nvi.index.utils.SearchConstants.APPROVAL_STATUS;
import static no.sikt.nva.nvi.index.utils.SearchConstants.ASSIGNEE;
import static no.sikt.nva.nvi.index.utils.SearchConstants.CONTRIBUTORS;
import static no.sikt.nva.nvi.index.utils.SearchConstants.ID;
import static no.sikt.nva.nvi.index.utils.SearchConstants.NUMBER_OF_APPROVALS;
import static no.sikt.nva.nvi.index.utils.SearchConstants.PUBLICATION_DETAILS;
import static no.sikt.nva.nvi.index.utils.SearchConstants.ROLE;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;
import no.sikt.nva.nvi.index.model.ApprovalStatus;
import org.opensearch.client.json.JsonData;
import org.opensearch.client.opensearch._types.FieldValue;
import org.opensearch.client.opensearch._types.query_dsl.BoolQuery;
import org.opensearch.client.opensearch._types.query_dsl.ExistsQuery;
import org.opensearch.client.opensearch._types.query_dsl.MatchQuery;
import org.opensearch.client.opensearch._types.query_dsl.NestedQuery;
import org.opensearch.client.opensearch._types.query_dsl.Query;
import org.opensearch.client.opensearch._types.query_dsl.QueryBuilders;
import org.opensearch.client.opensearch._types.query_dsl.RangeQuery;
import org.opensearch.client.opensearch._types.query_dsl.TermQuery;
import org.opensearch.client.opensearch._types.query_dsl.TermsQuery;
import org.opensearch.client.opensearch._types.query_dsl.TermsQueryField;

public class InstitutionSearch {

    private static final int MULTIPLE = 2;
    private static final CharSequence JSON_PATH_DELIMITER = ".";
    private static final String CREATOR_ROLE = "Creator";

    private final List<String> institutions;
    private final QueryFilterType filter;
    private final String username;
    private final String customer;

    public InstitutionSearch(Collection<String> institutions,
                             QueryFilterType filter,
                             String username,
                             String customer) {
        this.institutions = nonNull(institutions) ? new ArrayList<>(institutions) : emptyList();
        this.filter = filter;
        this.username = username;
        this.customer = customer;
    }

    public Query toQuery() {
        var query = specificMatch();

        return query.isEmpty()
                   ? createMatchAllQuery()
                   : mustMatch(query.toArray(Query[]::new));
    }

    private static Query mustMatch(Query... queries) {
        return new Query.Builder()
                   .bool(new BoolQuery.Builder().must(Arrays.stream(queries).toList()).build())
                   .build();
    }

    private List<Query> specificMatch() {
        var institutionQuery = createInstitutionQuery();
        var filterQuery = constructQueryWithFilter();

        return Stream.of(institutionQuery, filterQuery)
                    .filter(Optional::isPresent)
                    .map(Optional::get)
                    .toList();
    }

    private static Query createMatchAllQuery() {
        return QueryBuilders.matchAll().build()._toQuery();
    }

    private static Query multipleApprovalsQuery() {
        return mustMatch(rangeFromQuery(NUMBER_OF_APPROVALS, MULTIPLE));
    }

    private static Query nestedQuery(String path, Query... queries) {
        return new NestedQuery.Builder()
                   .path(path)
                   .query(mustMatch(queries))
                   .build()._toQuery();
    }

    private static Query statusQuery(String customer, ApprovalStatus status) {
        return nestedQuery(APPROVALS,
                           termQuery(customer, jsonPathOf(APPROVALS, ID)),
                           termQuery(status.getValue(), jsonPathOf(APPROVALS, APPROVAL_STATUS)));
    }

    private static Query termQuery(String value, String field) {
        return new TermQuery.Builder()
                   .value(new FieldValue.Builder().stringValue(value).build())
                   .field(field)
                   .build()._toQuery();
    }

    private static String jsonPathOf(String... args) {
        return String.join(JSON_PATH_DELIMITER, args);
    }

    private static Query rangeFromQuery(String field, int greaterThanOrEqualTo) {
        return new RangeQuery.Builder().field(field).gte(JsonData.of(greaterThanOrEqualTo)).build()._toQuery();
    }

    private static Query containsPendingStatusQuery() {
        return nestedQuery(APPROVALS, termQuery(PENDING.getValue(), jsonPathOf(APPROVALS, APPROVAL_STATUS)));
    }

    private Optional<Query> constructQueryWithFilter() {

        var aggregation = switch (filter) {
            case EMPTY_FILTER -> null;
            case PENDING_AGG -> statusQueryWithAssignee(customer, PENDING, false);

            case PENDING_COLLABORATION_AGG -> mustMatch(statusQueryWithAssignee(customer, PENDING, false),
                                                        multipleApprovalsQuery());

            case ASSIGNED_AGG -> mustMatch(statusQueryWithAssignee(customer, PENDING, true));

            case ASSIGNED_COLLABORATION_AGG -> mustMatch(statusQueryWithAssignee(customer, PENDING, true),
                                                         multipleApprovalsQuery());

            case APPROVED_AGG -> mustMatch(statusQuery(customer, APPROVED));

            case APPROVED_COLLABORATION_AGG -> mustMatch(statusQuery(customer, APPROVED),
                                                         containsPendingStatusQuery(),
                                                         multipleApprovalsQuery());

            case REJECTED_AGG -> mustMatch(statusQuery(customer, REJECTED));

            case REJECTED_COLLABORATION_AGG -> mustMatch(statusQuery(customer, REJECTED),
                                                         containsPendingStatusQuery(),
                                                         multipleApprovalsQuery());

            case ASSIGNMENTS_AGG -> mustMatch(assignmentsQuery(username, customer));
        };

        return Optional.ofNullable(aggregation);
    }


    private static Query assignmentsQuery(String username, String customer) {
        return nestedQuery(APPROVALS,
                           termQuery(customer, jsonPathOf(APPROVALS, ID)),
                           termQuery(username, jsonPathOf(APPROVALS, ASSIGNEE)));
    }

    private Optional<Query> createInstitutionQuery() {
        return !institutions.isEmpty() ? Optional.of(contributorQuery(institutions)) : Optional.empty();
    }

    private static Query termsQuery(List<String> values, String field) {
        var termsFields = values.stream().map(FieldValue::of).toList();
        return new TermsQuery.Builder()
                   .field(field)
                   .terms(new TermsQueryField.Builder().value(termsFields).build())
                   .build()._toQuery();
    }

    private static Query matchQuery(String value, String field) {
        return new MatchQuery.Builder().field(field)
                   .query(new FieldValue.Builder().stringValue(value).build())
                   .build()._toQuery();
    }

    private static Query contributorQuery(List<String> institutions) {
        return nestedQuery(jsonPathOf(PUBLICATION_DETAILS, CONTRIBUTORS),
                           QueryBuilders.bool().must(
                               termsQuery(institutions, [...]

2023-09-27 19:05 UTC, brinxmat commented on index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/SearchConstants.java
> +                   : mustMatch(appliedQueries);
```
        var institutionList = nonNull(institutions) && !institutions.isEmpty()
                                  ? List.of(institutions.split(","))
                                  : List.<String>of();
        var filterType = QueryFilterType.parse(filter)
                             .orElseThrow(() -> new IllegalStateException("unknown filter " + filter));
        var query = new InstitutionSearch.Builder()
                        .withInstitutions(institutionList)
                        .withFilter(filterType)
                        .withUsername(username)
                        .withCustomer(customer)
                        .build()
                        .toQuery();
```

2023-09-27 21:42 UTC, sondrev commented on nvi-evaluator/src/main/java/no/sikt/nva/nvi/evaluator/calculator/somejson.json
> +{
should not have been commited. I will delete

2023-09-28 05:28 UTC, brinxmat requested changes

2023-09-28 05:28 UTC, brinxmat commented on index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/CandidateQuery.java
> +                                   termsQuery(institutions, jsonPathOf(PUBLICATION_DETAILS, CONTRIBUTORS, AFFILIATIONS, PART_OF))
Loooooooong long lines (if you get the reference, cool, if not…meh…the lines are long and codacy is upset)

2023-09-28 05:28 UTC, brinxmat commented on index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/SearchConstants.java
> +    public static final String JSON_PATH_DELIMITER = ".";
I'm tempted to say that we should remove the class in its entirety…but as a new task so you can get this one merged

2023-09-28 07:44 UTC, monaullah commented on index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java
> +        var siktInstitutionId = "https://api.dev.nva.aws.unit.no/cristin/organization/194.0.0.0";
Not sure if I misunderstood the test, but should the affiliation you are searching for not be `"https://api.dev.nva.aws.unit.no/cristin/organization/194.0.0.1"`? Also, rename it to `ntnuSubUnitId`? 
```
var ntnuSubUnitId = "https://api.dev.nva.aws.unit.no/cristin/organization/194.0.0.1";
        var searchResponse =
            openSearchClient.search(ntnuSubUnitId, "", USERNAME, YEAR, CUSTOMER,
                                    DEFAULT_OFFSET_SIZE, DEFAULT_QUERY_SIZE);
```

2023-09-28 07:47 UTC, monaullah requested changes
Nice work, Sondre! See one comment on the test `shouldReturnSearchResultsWithContributorOfSearchedInstitutionWhenNotSearchingTopLevelInstititution`

2023-09-28 07:49 UTC, monaullah commented on index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java
> +        var siktInstitutionId = "https://api.dev.nva.aws.unit.no/cristin/organization/194.0.0.0";
Also, I think I would remove the other documents from the test to make sure I am testing the right thing:
```
@Test
    void shouldReturnSearchResultsWithContributorOfSearchedInstitutionWhenNotSearchingTopLevelInstititution()
        throws IOException, InterruptedException {
        addDocumentsToIndex(documentFromString("document_with_contributor_from_ntnu.json"));

        var ntnuSubUnitId = "https://api.dev.nva.aws.unit.no/cristin/organization/194.0.0.1";
        var searchResponse =
            openSearchClient.search(ntnuSubUnitId, "", USERNAME, YEAR, CUSTOMER,
                                    DEFAULT_OFFSET_SIZE, DEFAULT_QUERY_SIZE);

        assertThat(searchResponse.hits().hits(), hasSize(1));
    }
```

2023-09-28 08:01 UTC, monaullah approved these changes

2023-09-28 08:03 UTC, merged