fix(index-handlers): fix bug with missing id in contributor affiliations #NP-45427
BIBSYSDEV/nva-nvi pull request #148
Opened 2023-10-12 13:25 UTC by torbjokv

2023-10-16 11:40 UTC, hackon approved these changes

2023-10-16 11:40 UTC, hackon commented on index-handlers/src/main/java/no/sikt/nva/nvi/index/UpdateIndexHandler.java
> +             new Environment());
You can extract new Environment() into constant

2023-10-17 06:23 UTC, brinxmat requested changes

2023-10-17 06:23 UTC, brinxmat commented on index-handlers/src/main/java/no/sikt/nva/nvi/index/UpdateIndexHandler.java
> +        var sw = new StringWriter();
sw -> stringWriter, boring, I know

2023-10-17 06:23 UTC, brinxmat commented on index-handlers/src/test/java/no/sikt/nva/nvi/index/UpdateIndexHandlerTest.java
> +        Optional<CandidateDao> failingCandidateLookup = Optional.empty();
Just inline `Optional.<CandidateDao>empty()`

2023-10-17 06:23 UTC, brinxmat commented on index-handlers/src/test/java/no/sikt/nva/nvi/index/UpdateIndexHandlerTest.java
> +        var persistedCandidate = randomApplicableCandidate();
Inline

2023-10-17 06:23 UTC, brinxmat commented on nvi-commons/src/main/java/no/sikt/nva/nvi/common/queue/NviSendMessageResponse.java
> +    }
Builder for a single field?

2023-10-17 06:45 UTC, brinxmat approved these changes

2023-10-17 06:48 UTC, merged