feature: allow to reprocess failed candidates #NP-45510
BIBSYSDEV/nva-nvi pull request #206
Opened 2023-12-22 09:08 UTC by torbjokv

2023-12-22 11:50 UTC, torbjokv commented on event-handlers/src/main/java/no/sikt/nva/nvi/events/batch/RequeueDlqHandler.java
> +        return response.messages().isEmpty() || failedBatchesCount >= MAX_FAILURES;
An alternative or additional fail check, could be to use the sqs->ReceiveCount for each message, to make sure a message is not handled too many times

2024-01-02 08:06 UTC, monaullah requested changes

2024-01-02 08:06 UTC, monaullah commented on event-handlers/src/main/java/no/sikt/nva/nvi/events/batch/RequeueDlqHandler.java
> +                                                  periodRepository);
Extract to method?
```
var candidate = Candidate.fromRequest(() -> UUID.fromString(identifier), candidateRepository,
                                                  periodRepository);
var nviCandidate = NviCandidate.fromCandidate(candidate);

var updatedCandidate = Candidate.fromRequest(nviCandidate, candidateRepository, periodRepository);
```

2024-01-02 10:03 UTC, torbjokv commented on event-handlers/src/main/java/no/sikt/nva/nvi/events/batch/RequeueDlqHandler.java
> +        return response.messages().isEmpty() || failedBatchesCount >= MAX_FAILURES;
will not do this at right now

2024-01-02 10:15 UTC, monaullah approved these changes

2024-01-02 11:36 UTC, merged