Np 46551 Index document, approval status New
BIBSYSDEV/nva-nvi pull request #293
Opened 2024-04-12 12:52 UTC by monaullah

Jira task: NP-46551 Index document, logical status New

Same "logic" as in ticket expansion in publication-api. If approval is pending and unassigned, set status New in index document.

2024-04-15 19:26 UTC, brinxmat approved these changes
Mentioning why perhaps findAny is what you want, but the optimalisation is not a huge issue

2024-04-15 19:26 UTC, brinxmat commented on index-handlers/src/main/java/no/sikt/nva/nvi/index/model/NviCandidateIndexDocument.java
> +                   .findFirst()
https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#findAny--

2024-04-16 05:59 UTC, truhacevkir approved these changes

2024-04-16 08:04 UTC, StigNorland requested changes

2024-04-16 08:23 UTC, monaullah commented on nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java
> +        return no.sikt.nva.nvi.common.service.model.ApprovalStatus.PENDING.equals(approval.getStatus())
Yes, keeping business object `Approval` and index document model separate

2024-04-16 08:41 UTC, truhacevkir approved these changes

2024-04-16 08:46 UTC, merged