Np 46897 NviPeriod, refactor
BIBSYSDEV/nva-nvi pull request #323
Opened 2024-06-05 11:11 UTC by monaullah

2024-06-05 13:08 UTC, monaullah commented on nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/Validator.java
> +                field.setAccessible(true);
Thanks, modified the check to known class

2024-06-06 04:38 UTC, brinxmat requested changes

2024-06-06 04:38 UTC, brinxmat commented on nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/NviPeriod.java
> +        request.validate();
Might do this:

```
    var period = NviPeriod.fromRequest(NviPeriodRequest request); // this method does request.validate()
    if (period.exists(periodRepository)) {
        throw new PeriodAlreadyExistsException(String.format(PUBLISHING_YEAR_EXISTS, period.publishingYear()))
    }
    period.persist(periodRepository);
    return period.fetch(periodRepository);
```

2024-06-06 08:31 UTC, brinxmat approved these changes

2024-06-06 08:36 UTC, truhacevkir approved these changes

2024-06-06 08:37 UTC, merged