create nvi period handler
BIBSYSDEV/nva-nvi pull request #34
Opened 2023-08-22 08:07 UTC by truhacevkir

2023-08-23 09:04 UTC, anetteOlli requested changes

2023-08-23 09:06 UTC, monaullah commented on docs/openapi.yaml
> +  /nvi-period:
Enough with just period? Since the path before is /scientific-index?

2023-08-23 13:10 UTC, truhacevkir commented on nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/NviServiceTest.java
> +                   .withPublishingYear(randomString())
Tenkte å legge til validering når servicen er implementert, men kan også legge inn nå.

2023-08-24 11:50 UTC, monaullah commented on docs/openapi.yaml
> +      responses:
Add 400 here?

2023-08-24 11:55 UTC, monaullah commented on nvi-rest/src/test/java/no/sikt/nva/nvi/rest/CreateNviPeriodHandlerTest.java
> +
shouldReturnBadRequestWhenRequestIsInvalid?

2023-08-24 11:56 UTC, monaullah commented on nvi-rest/src/main/java/no/sikt/nva/nvi/rest/utils/RequestUtil.java
> +public final class RequestUtil {
Nice! Could move to commons in future

2023-08-24 13:18 UTC, monaullah approved these changes

2023-08-24 13:18 UTC, merged