UpsertAssigneeHandler implemented
BIBSYSDEV/nva-nvi pull request #81
Opened 2023-09-08 13:17 UTC by truhacevkir

2023-09-08 14:02 UTC, truhacevkir commented on nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/NviService.java
> +    }
In my opinion this object should be call Approval and not ApprovalStatus
And then we can check if update is status, assignee or note and refactor it to do right things

2023-09-10 16:26 UTC, brinxmat requested changes

2023-09-10 16:26 UTC, brinxmat commented on nvi-rest/src/main/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandler.java
> +    private boolean hasAccessRight(User user) {
isSomthingToDoWithSpecificRoleInApplication

2023-09-10 16:26 UTC, brinxmat commented on nvi-rest/src/main/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandler.java
> +                   .filter(approval -> approval.institutionId().equals(input.institutionId()))
Every inline check/filter should be pulled out with a good name.

2023-09-10 16:26 UTC, brinxmat commented on nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandlerTest.java
> +    void shouldUpdateAssignee() throws IOException {
When?

2023-09-10 16:26 UTC, brinxmat commented on nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandlerTest.java
> +    void shouldRemoveAssignee() throws IOException {
When?

2023-09-10 16:26 UTC, brinxmat commented on nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandlerTest.java
> +public class UpsertAssigneeHandlerTest extends LocalDynamoTest {
Not public

2023-09-10 16:26 UTC, brinxmat commented on nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandlerTest.java
> +        context = mock(Context.class);
new FakeContext() ?

2023-09-10 16:26 UTC, brinxmat commented on nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandlerTest.java
> +        var requestBody = new ApprovalDto(assignee, approvalToUpdate.institutionId());
Quite a few places
```
    private InputStream createRequest(String assignee) throws JsonProcessingException {
        var candidate = nviService.upsertCandidate(randomApplicableCandidateBuilder()).orElseThrow();
        var approvalToUpdate = candidate.approvalStatuses().get(0);
        var requestBody = new ApprovalDto(assignee, approvalToUpdate.institutionId());
        return createRequest(randomUUID(), requestBody, assignee);
    }
```

2023-09-10 16:26 UTC, brinxmat commented on nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandlerTest.java
> +    private void persistRandomAssignee(Candidate candidate) {
Is this a good name?

2023-09-11 09:02 UTC, truhacevkir commented on nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/NviService.java
> +    }
Have refactored following to this:

```
    private DbApprovalStatus toUpdatedApprovalStatus(DbApprovalStatus oldApprovalStatus,
                                                     DbApprovalStatus newApprovalStatus) {
        if (updateIsAssignee(oldApprovalStatus, newApprovalStatus)) {
            return updateAssignee(oldApprovalStatus, newApprovalStatus);
        } else {
            return updateStatus(oldApprovalStatus, newApprovalStatus);
        }
    }

    private static DbApprovalStatus updateStatus(DbApprovalStatus oldApprovalStatus,
                                                        DbApprovalStatus newApprovalStatus) {
        return switch (newApprovalStatus.status()) {
            case APPROVED, REJECTED -> finalizeStatus(oldApprovalStatus, newApprovalStatus);
            case PENDING -> resetStatus(oldApprovalStatus);
        };
    }

    private static boolean updateIsAssignee(DbApprovalStatus oldApprovalStatus, DbApprovalStatus newApprovalStatus) {
        return oldApprovalStatus.status().equals(newApprovalStatus.status());
    }
```

There will be more refactoring when we will add endpoint for updating notes.

2023-09-11 12:23 UTC, hackon approved these changes

2023-09-11 12:23 UTC, hackon commented on nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/NviService.java
> +        return oldApprovalStatus.status().equals(newApprovalStatus.status());
Wouldn't it make more sense to compare assignee to newAssignee?

2023-09-11 12:29 UTC, merged