forbidding any operation on approval when period has been closed
BIBSYSDEV/nva-nvi pull request #90
Opened 2023-09-15 11:56 UTC by truhacevkir

2023-09-15 12:35 UTC, truhacevkir commented on nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateHandler.java
> +                   .map(candidate -> CandidateResponse.fromCandidate(candidate, service))
I think it is not the best implementation, but otherwise i have to fetch candidate and period on the top of the method and pass it here.

2023-09-19 13:22 UTC, ketilaa requested changes

2023-09-19 13:22 UTC, ketilaa commented on nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/ReportStatus.java
> +public enum ReportStatus {
`PeriodStatus`

2023-09-19 13:22 UTC, ketilaa commented on nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/ReportStatus.java
> +    REPORTABLE("Reportable"), NOT_REPORTABLE("NotReportable");
NO_PERIOD("NoPeriod"),
OPEN_PERIOD("OpenPeriod"),
CLOSED_PERIOD("ClosedPeriod");

2023-09-19 13:22 UTC, ketilaa commented on nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpdateNviCandidateStatusHandlerTest.java
Add test for case where period has not been created yet?

2023-09-19 13:29 UTC, truhacevkir commented on nvi-rest/src/main/java/no/sikt/nva/nvi/rest/create/CreateNoteHandler.java
> +        RequestUtil.validatePeriod(requestInfo, service);
I mean no, since it has not been implement there before.

2023-09-21 07:12 UTC, anetteOlli approved these changes

2023-09-22 08:15 UTC, ketilaa commented on nvi-rest/src/test/java/no/sikt/nva/nvi/rest/create/CreateNoteHandlerTest.java
> +        assertThat(response.getStatusCode(), is(equalTo(HttpURLConnection.HTTP_BAD_REQUEST)));
I think 409 Conflict is a better status code to return. 400 means the server is not able to understand the request, but the case here is that the server state does not allow the request.

2023-09-25 11:32 UTC, closed without merging