updating status verification
BIBSYSDEV/nva-nvi pull request #94
Opened 2023-09-19 13:14 UTC by truhacevkir

2023-09-20 08:08 UTC, monaullah requested changes
See description in Jira task:

> then the approval status is set back to Pending and the rejection note that followed the rejection is removed

I think this task is blocked by https://unit.atlassian.net/browse/NP-45218 / https://github.com/BIBSYSDEV/nva-nvi/pull/92

Finish https://github.com/BIBSYSDEV/nva-nvi/pull/92 first?

2023-09-22 08:56 UTC, ketilaa approved these changes

2023-09-26 05:33 UTC, brinxmat approved these changes
See comment

2023-09-26 05:33 UTC, brinxmat commented on nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpdateNviCandidateStatusHandlerDbTest.java
> +        return candidate.approvalStatuses().get(0).copy()
In another PR, we need to be able to easily access a given approval in a sensible way…i.e. what is a unique and relevant way of accessing an approval? Probably, `Optional<ApprovalStatus> approvalStatuses.getApprovalForCustomer(URI customer)`

2023-10-04 10:09 UTC, closed without merging